DROP TABLE GAME CASCADE CONSTRAINTS;

DROP TABLE BOARD_GAME CASCADE CONSTRAINTS;

DROP TABLE VIDEO_GAME_DISK CASCADE CONSTRAINTS;

DROP TABLE VIDEO_GAME_DIGITAL CASCADE CONSTRAINTS;

DROP TABLE COUPON CASCADE CONSTRAINTS;

DROP TABLE CONSOLE CASCADE CONSTRAINTS;

DROP TABLE COMPUTER CASCADE CONSTRAINTS;

CREATE TABLE GAME (
    GAMETYPE VARCHAR2(10),
    GAMEID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(20),
    PRICE NUMBER(7, 2),
    RATING VARCHAR2(4)
);

CREATE TABLE BOARD_GAME(
    BOARDGAMETYPE VARCHAR2(10),
    BOARDGAMEID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(20),
    PRICE NUMBER(5, 2),
    RATING VARCHAR2(4),
    PIECES NUMBER (6, 0)
);

CREATE TABLE VIDEO_GAME_DISK(
    GAMEDISKTYPE VARCHAR2(10),
    GAMEDISKID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(20),
    PRICE NUMBER(5, 2),
    RATING VARCHAR2(4),
    PLATFORM VARCHAR2(20),
    PUBLISHER VARCHAR2(20)
);

CREATE TABLE VIDEO_GAME_DIGITAL(
    DIGITALGAMETYPE VARCHAR2(10),
    DIGITALGAMEID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(20),
    PRICE NUMBER(5, 2),
    RATING VARCHAR2(4),
    PLATFORM VARCHAR2(20),
    GAME_SIZE NUMBER(6, 3)
);

CREATE TABLE COUPON (
    COUPONTYPE VARCHAR2(10),
    COUPONID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT VARCHAR2(20),
    AMOUNT NUMBER(4, 2),
    TYPE VARCHAR2(20)
);

CREATE TABLE CONSOLE(
    CONSOLETYPE VARCHAR2(10),
    CONSOLEID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEVICENAME VARCHAR2(20),
    PRICE NUMBER(5, 2)
);

CREATE TABLE COMPUTER(
    COMPUTERTYPE VARCHAR2(10),
    COMPUTERID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEVICENAME VARCHAR2(20),
    STORAGE NUMBER(8, 2),
    RAM NUMBER (4, 0),
    PRICE NUMBER(7, 2)
);

-- TODO
INSERT INTO GAME(
    TITLE,
    PRICE,
    RATING
) VALUES(
    'UNO',
    13.99,
    '6+'
);

INSERT INTO BOARD_GAME(
    TITLE,
    PRICE,
    RATING,
    PIECES
) VALUES(
    'board',
    'Chess',
    33.85,
    '8+',
    32
);

INSERT INTO VIDEO_GAME_DISK(
    TITLE,
    PRICE,
    RATING,
    PLATFORM,
    PUBLISHER
) VALUES(
    'disk',
    'God of War',
    63.85,
    '16+',
    'PS5',
    'PEOPLE'
);

INSERT INTO VIDEO_GAME_DIGITAL(
    TITLE,
    PRICE,
    RATING,
    PLATFORM,
    GAME_SIZE
) VALUES(
    'digital',
    'Terraria',
    23.85,
    '10+',
    'PC',
    3.5
);

INSERT INTO COMPUTER(
    DEVICENAME,
    STORAGE,
    RAM,
    PRICE
) VALUES(
    'pc',
    'ASUS Desktop-01',
    1.8,
    16,
    999.99
);

INSERT INTO CONSOLE(
    DEVICENAME,
    PRICE
) VALUES(
    'console',
    'Nintendo Switch',
    700
);

INSERT INTO CONSOLE(
    DEVICENAME,
    PRICE
) VALUES(
    'console',
    'Playstation 5',
    900
);

INSERT INTO COUPON(
    AMOUNT,
    TYPE
) VALUES(
    'discount',
    20,
    'Discount'
);

COMMIT;